### ISSUE TITLE
Azure: get seems to sometimes fail

### ISSUE THREAD

**Issue by Fristi** [fs2-blobstore/fs2-blobstore#333]
During a heavy test, I see sometimes the get failing:

```
java.lang.Error: received record [java.nio.HeapByteBuffer[pos=0 lim=615 cap=615]] in invalid state [UpstreamCompletion]
	at fs2.interop.reactivestreams.StreamSubscriber$.$anonfun$fsm$5(StreamSubscriber.scala:119)
	at cats.effect.concurrent.Ref$SyncRef.spin$4(Ref.scala:316)
	at cats.effect.concurrent.Ref$SyncRef.$anonfun$modify$1(Ref.scala:320)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:361)
	at zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:775)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

I'm making a test case which hopefully will demonstrate the issue

**Comment by Fristi** [comment]
There was a quite recent change for fs2-reactive-streams typelevel/fs2@a9ff266

In this fix the onNext/onSubscribe effects are evaluated synchronously instead of asynchronously.

In conclusion, the fix was to update fs2-reactive-streams to the latest version and the problem was not in the ZIO interop.

There is still an outstanding issue with it though typelevel/fs2#2260

I've added a prop test in #334 to make sure this behavior is tested, feel free to merge if it's useful
