### ISSUE TITLE
Stream not completing when cancelling a CompletableFuture after passing to blobstore.util.liftJavaFuture

### ISSUE THREAD

**Issue by MattDaveyI** [fs2-blobstore/fs2-blobstore#434]
Hey,

I've been using the following artefacts for this example:

```
"com.github.fs2-blobstore" %% "core" % "0.7.3",
"com.github.fs2-blobstore" %% "s3"   % "0.7.3"
```

I've been fiddling around with the S3Store a bit more and ran into some unexpected behaviour with what appeared to be the HTTP client from the S3 client cancelling the future and the stream not terminating.  I've had trouble reproducing exactly, but I've tried to create a simpler example to see if this could have happened.

NB: It's definitely possible that I'm either misunderstanding something, or that my expectations on what should happen are wrong - apologies if so.

```scala
object Test extends IOApp {
  import scala.concurrent.duration._

  private val cancelFuture = (c: CompletableFuture[String]) => IO(c.cancel(true)).void
  private val successfulFuture = (c: CompletableFuture[String]) => IO(c.complete("Success!")).void
  private val failFuture = (c: CompletableFuture[String]) => IO(c.completeExceptionally(new Exception("Oh no!"))).void

  override def run(args: List[String]): IO[ExitCode] = {
    def stream(completeFuture: CompletableFuture[String] => IO[Unit]): IO[Unit] =
      fs2.Stream(123)
        .evalMap(_ => doInCompletableFuture(completeFuture))
        .compile
        .drain

    for {
      s <- stream(successfulFuture).attempt
      _ <- IO(println(s"successfulFuture completed with $s"))
      f <- stream(failFuture).attempt
      _ <- IO(println(s"failFuture completed with $f"))
      c <- stream(cancelFuture).attempt
      _ <- IO(println(s"cancelFuture completed with $c"))
    } yield ExitCode.Success
  }

  private def doInCompletableFuture(completeFuture: CompletableFuture[String] => IO[Unit]): IO[Unit] = {
    val c = new CompletableFuture[String]()

    val r = for {
      // Just doing it in the background to try to make sure that the CompletableFuture is not completed when 
      // we enter the liftJavaFuture method
      _ <- IO.sleep(5.seconds).flatMap(_ => completeFuture(c)).background
      _ <- Resource.eval(blobstore.util.liftJavaFuture(IO.pure(c)))
    } yield ()

    r.use(IO.pure)
  }

}
```

I'd expected the program to complete, but it hangs indefinitely on the `stream(cancelFuture).attempt` .  Is this expected behaviour and I'm just doing something silly?

**Comment by MattDaveyI** [comment]
Okay, I did get the exception again:

```
java.io.IOException: Request cancelled
	at software.amazon.awssdk.http.nio.netty.internal.FutureCancelHandler.exceptionCaught(FutureCancelHandler.java:43)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:300)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:279)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:271)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireExceptionCaught(CombinedChannelDuplexHandler.java:424)
	at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:92)
	at io.netty.channel.CombinedChannelDuplexHandler$1.fireExceptionCaught(CombinedChannelDuplexHandler.java:145)
	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:143)
	at io.netty.channel.CombinedChannelDuplexHandler.exceptionCaught(CombinedChannelDuplexHandler.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:300)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:279)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:271)
	at io.netty.handler.ssl.SslHandler.exceptionCaught(SslHandler.java:1104)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:300)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:279)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:271)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:300)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:279)
	at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:907)
	at software.amazon.awssdk.http.nio.netty.internal.NettyRequestExecutor.lambda$null$1(NettyRequestExecutor.java:120)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)
```

The exception is logged at debug level.

I'm using a chunk size of 100 MB in the S3Store, and doing a putObject without the Content Size and with a 100GB object.  I can see that the Multipart Upload is being created, so I imagine it's just my client timing out on the request to put the part - I can probably fiddle with the HTTP Client configuration for my S3 client to increase the timeout and make this error less likely, but I suspect there might be an issue with the stream not terminating in this case (but as I say, my fs2 knowledge is not good and maybe I'm misunderstanding something or doing something stupid).

**Comment by MattDaveyI** [comment]
I think I'm just being an idiot, I think the Http4s server cancels the endpoint invoking the stream so we don't expect any completion for it (I'm using too many new technologies at once, it seems!).
