### ISSUE TITLE
Path breaks on file name with spaces in them

### ISSUE THREAD

**Issue by MaT1g3R** [fs2-blobstore/fs2-blobstore#71]
When there is a space in the `Path`, it throws an `IllegalArgumentException`

```java
Exception in thread "main" java.lang.IllegalArgumentException: Unable to extract path from 'tmp/docs/reports/0003b97c-d6bc-4496-96b4-3dc128fbdc49-my report.csv'
	at blobstore.Path$.$anonfun$apply$1(Path.scala:219)
	at scala.Option.getOrElse(Option.scala:201)
	at blobstore.Path$.apply(Path.scala:219)
	at blobstore.PathOps$AppendOps.$div(PathOps.scala:18)
	at com.garnercorp.Main$.delayedEndpoint$com$garnercorp$Main$1(Main.scala:11)
	at com.garnercorp.Main$delayedInit$body.apply(Main.scala:6)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1(App.scala:73)
	at scala.App.$anonfun$main$1$adapted(App.scala:73)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:921)
	at scala.App.main(App.scala:73)
	at scala.App.main$(App.scala:71)
	at com.garnercorp.Main$.main(Main.scala:6)
	at com.garnercorp.Main.main(Main.scala)

```

To reproduce:

```scala
import blobstore.Path
import blobstore.PathOps._

object Main extends App {
  val root = "/tmp/docs/reports"
  val goodFileName = "0003b97c-d6bc-4496-96b4-3dc128fbdc49-my-report.csv"
  val badFileName = "0003b97c-d6bc-4496-96b4-3dc128fbdc49-my report.csv"
  println(Path(root) / goodFileName) // fine
  println(Path(root) / badFileName) // blows up
}
```

**Comment by gafiatulin** [comment]
@MaT1g3R thanks for reporting. Fixed in #72.
